school_schema_layer_1 = {
    "institution_data": {
        "name_en": "INSTNM - hd2019",
        "name_jp": "",
        "uuid": "",
        "opeid": "OPEID - hd2019",
        "local_url": "",
        "campus": {
            "address": "ADDR - hd2019",
            "city": "CITY - hd2019",
            "state_postid": "STABBR - hd2019",
            "zip": "ZIP - hd2019",
            "bea_regions": "OBEREG - hd2019",
            "geolocation": {
                "latitude": "LATUTIDE - hd2019",
                "longitude": "LONGITUDE - hd2019",
            },
            "school_system": "F1SYSCOD - hd2019",
            "urbanization_level": "LOCALE - hd2019",
        },
        "housing": {
            "provides_oncampus_housing": "ROOM - ic2019",
            "oncampus_dorm_capacity": "ROOMCAP - ic2019",
            "yearly_room_charge": "ROOMAMT - ic2019",
            "board_meal_plan": "BOARD - ic2019",
            "meals_per_week_in_board": "MEALSWK - ic2019",
            "yearly_board_charge": "BOARDAMT - ic2019",
            "yearly_room_and_board_charge": "RMBRDAMT - ic2019",
        },
        "official_resources": {
            "admissions": "ADMINURL - hd2019",
            "online_application": "APPLURL - hd2019",
            "net_price_calculator": "NPRICURL - hd2019",
            "financial_aid": "FAIDURL - hd2019",
            "homepage": "WEBADDR - hd2019",
        },
        "classifications": {"carnegie_classification": "SECTOR - hd2019"},
        "student_faculty_ratio": "STUFACR - ef2019d",
        "fulltime_retention_rate": "RET_PCF - ef2019d",
        "students": {
            "institution_size_category": "INSTSIZE - hd2019",
            "total_men": "EFYTOTLM - effy2019",
            "total_women": "EFYTOTW - effy2019",
            "breakdown_by_race": {
                "hispanic_or_latino": "EFYHISPT - effy2019",
                "american_indian_or_alaska_native": "EFYAIANT - effy2019",
                "asian": "EFYASIANT - effy2019",
                "black_or_african_american": "EFYBKAAT - effy2019",
                "native_hawaiian_or_other_pacific_islander": "EFYNHPIT - effy2019",
                "white": "EFYWHIT - effy2019",
                "two_or_more": "EFY2MORT - effy2019",
            },
            "breakdown_by_race_and_sex": {
                "hispanic_or_latino_men": "EFYHISPM - effy2019",
                "hispanic_or_latino_women": "EFYHISPW - effy2019",
                "american_indian_or_alaska_native_men": "EFYAIANM - effy2019",
                "american_indian_or_alaska_native_women": "EFYAIANW - effy2019",
                "asian_men": "EFYASIANM - effy2019",
                "asian_women": "EFYASIANW - effy2019",
                "black_or_african_american_men": "EFYBKAAM - effy2019",
                "black_or_african_american_women": "EFYBKAAW - effy2019",
                "native_hawaiian_or_other_pacific_islander_men": "EFYNHPIM - effy2019",
                "native_hawaiian_or_other_pacific_islander_women": "EFYNHPIW - effy2019",
                "white_men": "EFYWHIM - effy2019",
                "white_women": "EFYWHIW - effy2019",
            },
        },
        "admissions": {
            "is_open_admissions": "OPENADMP - ic2019",
            "requirements": {
                "gpa": "ADMCON1 - adm2019",
                "school_rank": "ADMCON2 - adm2019",
                "school_record": "ADMCON3 - adm2019",
                "college_preparatory_programs": "ADMCON4 - adm2019",
                "recommendation_letters": "ADMCON5 - adm2019",
                "formal_demonstration": "ADMCON6 - adm2019",
                "admission_test_scores": "ADMCON7 - adm2019",
                "toefl": "ADMCON8 - adm2019",
                "other_tests": "ADMCON9 - adm2019",
            },
            "sat": {
                "eng_25th_percentile": "",
                "eng_75th_percentile": "",
                "math_25th_percentile": "",
                "math_75th_percentile": "",
            },
            "act": {
                "comp_25th_percentile": "",
                "comp_75th_percentile": "",
                "eng_25th_percentile": "",
                "eng_75th_percentile": "",
                "math_25th_percentile": "",
                "math_75th_percentile": "",
            },
            "population": {
                "applicants_men": "",
                "applicants_women": "",
                "admissions_men": "",
                "admissions_women": "",
                "applicants_total": "",
                "admissions_total": "",
                "num_submitting_sat": "",
                "percent_submitting_sat": "",
                "num_submittin_act": "",
                "percent_submitting_act": "",
            },
        },
        "education": {
            "calendar_system": "",
            "top_3_largest_programs": "",
        },
        "sports": {
            "is_member_of_national_athletic_association": "",
            "athletic_orginizations": [],
        },
        "tuition": {
            "in_state": {
                "tuition_and_fees": "",
                "tuition": "",
                "fees": "",
            },
            "out_of_state": {
                "tuition_and_fees": "",
                "tuition": "",
                "fees": "",
            },
            "books_and_supplies": "",
            "other_expenses": "",
            "room_and_board_on_campus": "",
            "room_and_board_off_campus": "",
            "other_expenses_off_campus": "",
        },
        "faculty": {
            "fulltime_instructional_staff_total": "",
            "breakdown_by_rank": {
                "professors": "",
                "associate_professors": "",
                "assitant_professors": "",
                "other": "",
            },
        },
        "library": {
            "books_physical_total": "",
            "books_digital_total": "",
            "databases_digital_total": "",
            "media_physical_total": "",
            "media_digital_total": "",
        },
        "rankings": {},
    },
    "majors": {},
}
